---
- name: Install apache
  hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

  tasks:

    - name: add an environment variable to the remote user's shell
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR='
        line: 'ENV_VAR=value'
      become: false

    - name: get the value of an evironment variable
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      #      shell: 'echo $ENV_VAR'
      register: foo

    - name: debug - show ansible variable value
      debug: 
        msg: "The value of the variable is {{ lookup('env','ENV_VAR') }}"

    - name: ensure apache is installed
      yum:
        name: httpd
        state: present

    - name: copy config file
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart apache

    - name: ensure apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: true

